### ISSUE TITLE
Add popups when first using certain tools

### ISSUE THREAD

**Issue by AntiToni** [automatarium/automatarium#468]
### Proposed feature or solution

Have popups that give further information when you use a tool for the first time.

i.e. when setting a final state in a TM, explain how halting works

### Sub-Tasks
- [x] Create event which detects when tool is used
- [x] Save whether popup has been shown in zustand usePopupsStore.js\
- [x] Design popup/use existing popup design
- [x] Implement popup

**Comment by s3897720** [comment]
Was merged but not automerged. Closing as per discussion
